# Importing Data

In [1]:
import pandas as pd

data = pd.read_csv('TestPad_PCB_XYRGB_V2.csv')

In [2]:
display(data)

          X    Y         R         G         B  Grey
0       105    0  0.909804  0.976471  0.937255     0
1       106    0  0.792157  0.901961  0.843137     0
2       107    0  0.631373  0.788235  0.694118     0
3       108    0  0.474510  0.670588  0.556863     0
4       109    0  0.341176  0.584314  0.439216     0
...     ...  ...       ...       ...       ...   ...
723547  961  778  0.745098  0.917647  0.811765     0
723548  962  778  0.749020  0.917647  0.811765     0
723549  963  778  0.752941  0.909804  0.807843     0
723550  964  778  0.756863  0.905882  0.807843     0
723551  965  778  0.752941  0.901961  0.803922     0

[723552 rows x 6 columns]

# Missing Values Count

In [3]:
print("Missing values:\n", data.isnull().sum())

Missing values:
 X       0
Y       0
R       0
G       0
B       0
Grey    0
dtype: int64

# Variable Data Types

In [4]:
print("Data types:\n", data.dtypes)

Data types:
 X         int64
Y         int64
R       float64
G       float64
B       float64
Grey      int64
dtype: object

# Adding Interaction Terms
Might come in handy later

In [5]:
data['Intensity'] = (data['R'] + data['G'] + data['B']) / 3
data['R_G_ratio'] = data['R'] / data['G']
data['R_B_ratio'] = data['R'] / data['B']
data['G_B_ratio'] = data['G'] / data['B']

In [6]:
display(data)

,X,Y,R,G,B,Grey,Intensity,R_G_ratio,R_B_ratio,G_B_ratio
0,105,0,0.909804,0.976471,0.937255,0,0.941176,0.931727,0.970711,1.041841
1,106,0,0.792157,0.901961,0.843137,0,0.845752,0.878261,0.939535,1.069767
2,107,0,0.631373,0.788235,0.694118,0,0.704575,0.800995,0.909605,1.135593
3,108,0,0.474510,0.670588,0.556863,0,0.567320,0.707602,0.852113,1.204225
4,109,0,0.341176,0.584314,0.439216,0,0.454902,0.583893,0.776786,1.330357
...,...,...,...,...,...,...,...,...,...,...
723547,961,778,0.745098,0.917647,0.811765,0,0.824837,0.811966,0.917874,1.130435
723548,962,778,0.749020,0.917647,0.811765,0,0.826144,0.816239,0.922705,1.130435
723549,963,778,0.752941,0.909804,0.807843,0,0.823529,0.827586,0.932039,1.126214
723550,964,778,0.756863,0.905882,0.807843,0,0.823529,0.835498,0.936893,1.121359
723551,965,778,0.752941,0.901961,0.803922,0,0.819608,0.834783,0.936585,1.121951